spring:
  datasource:
    username: fdt
    password: fdt
    url: jdbc:mysql://8.138.44.135/:3306/user_center?
    driver-class-name: com.mysql.jdbc.Driver
#    session失效时间
  session:
    timeout: 86400